### ISSUE TITLE
Exception in thread "main" java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by abhinavkushagra** [stefano-bragaglia/Multi-Sentence-Compression#1]
I just want to know where to put the bin files i.e., en-sent.bin and en-token.bin. I tried adding new classpathentry but seems like it's giving me the same error again and again. BTW, I'm using Eclipse IDE.

**Comment by stefano-bragaglia** [comment]
Hi!

They should go in `/src/main/resources/`... Actually they are already there!

I haven't been using Eclipse in a long time, as I am using Idea now...
I remember however that, back in the days, I had so many problems importing Idea projects into Eclipse... 
The only thing that worked for me was to create an empty project and move files there manually...

I'm working on a Python version of this package that I'll release asap, if it helps...

Stefano

**Comment by abhinavkushagra** [comment]
Actually, I've moved files manually. But, I think for the line  ` InputStream stream = OpenNLP.class.getResourceAsStream("en-sent.bin");`
 in getSentenceDetector( ) of class OpenNLP, I need some changes in my classpath of Eclipse Project. I did some changes according to the location of the resources provided but I am still unsuccessful.

**Comment by stefano-bragaglia** [comment]
In theory (I'm never 100% sure of what is going on when using class loaders), the string that you pass to the `getResourceasStream` method is the relative path for the file (i.e.: `en-sent.bin`) with respect to the `src/main/resource` folder... maybe you can try adding a `./` in front of it?

Alternatively (as it is generally considered a better practice) you can create an `OpenNLP` folder in your home and move all the models files there. Then use absolute paths in the `getResourceAsStream` method... I usually duplicate and have a copy of the models in the `resource` folders so that everything that is needed by the project is bundled to gather with it...

Anyway, have you tried to clone the project and run it from the command line through `gradle` before loading it in any IDE?

Alternatively you can try to replace the OpenNLP stuff with Stanford CoreNLP or ClearNLP (now NLP4j) equivalent (both code and models can be imported through 'gradle' or 'maven'). It shouldn't be too difficult, as in the end you just need a sentence detector, a tokeniser and a PoS tagger. If you're not familiar with NLP tools, consider that - as a rule of the thumb- both Stanford and NLP4j are more accurate than the standard models of OpenNLP; however Stanford APIs are a bit more complicated (there is a implied version available, which is still not as user friendly as OpenNLP) and NLP4j is very memory-hungry...

Hope this helps... let me know if I can further assist!

**Comment by abhinavkushagra** [comment]
No, Sir. I haven't tried `gradle` before. But my problem has been solved now and all thanks to you.
What I did is, I replaced the line `InputStream stream = OpenNLP.class.getResourceAsStream("en-sent.bin");`  with  `Input Stream stream = new BufferedInputStream(new FileInputStream(new File(_filepath_)));` . It solved my problem. But I need to know, where would be the graph generated?

**Comment by stefano-bragaglia** [comment]
I see, maybe it was due to a different version of Java?

`gradle` (or any similar tool) is very convenient as it handles, among other things, the importing of jar, the building, the testing and also the execution of your code...

If I remember right, the graph generated when the application is run is stored in a folder on your machine in Neo4j format. If you want to visualise it, you have to download Neo4j community edition from Neo4j website and run it. Make sure to tell Neo4j to use the data that is in the folder I was mentioning above. Once the server is up and running, point your browser to `http://localhost:7474` (default username and password are: `neo4j`/`neo4j`) and you can interact with the graph from there.

Glad that it helped! 
Happy summarisation!

**Comment by abhinavkushagra** [comment]
Thank you for all your help, Sir. :)
